### ISSUE TITLE
Other Markets not working

### ISSUE THREAD

**Issue by m4rc3l** [chrisek/PT_Tracker#10]
Has the market dropdown any impact on the sheet? When I change to ETH I cant see any difference. And the currency is still calculated in BTC. So I can choose now EUR instead of USD, but since I use ETH-market, the charts get messed up.  Cause the PT Dump is only numbers and the spreadsheet only calculates BTC.  So I got my Deposit in EUR that gives me 10ETH Balance, but the output shows a balance of 86.000€ cause its calculated 10BTC

**Comment by chrisek** [comment]
Corrected, now it works, if yiu find any errors please make a contact.
