### ISSUE TITLE
Total Capital USD on Dashboard differences from Current Capital

### ISSUE THREAD

**Issue by cryptroid** [chrisek/PT_Tracker#11]
So I will attach some screen shots, but the numbers dont seem to make sense to me.

On the dashboard, the total capital in lower right hand corner says 6k something and tell me I have EARNED x amount and if you go to the charts page, itll tell me I am in the whole $600 and my balance is 5k something...

![screen shot 2018-01-18 at 12 39 02 am](https://user-images.githubusercontent.com/35219101/35088254-157cd660-fbe8-11e7-9bcf-00280848ae2e.png)
![screen shot 2018-01-18 at 12 39 10 am](https://user-images.githubusercontent.com/35219101/35088255-1596e122-fbe8-11e7-83e7-53d9f0fec216.png)
![screen shot 2018-01-18 at 12 39 23 am](https://user-images.githubusercontent.com/35219101/35088256-15acaa8e-fbe8-11e7-838b-4e6cb4eed95e.png)

**Comment by chrisek** [comment]
Corrected!

**Comment by cryptroid** [comment]
So I have to re downloaded?  have a link?

*Andrew Hamlin*
407.773.9942
hamlinjandrew@gmail.com

**Comment by cryptroid** [comment]
Thanks dude!
