### ISSUE TITLE
'Price that day' is not working

### ISSUE THREAD

**Issue by m4rc3l** [chrisek/PT_Tracker#12]
In the Deposit all prices in that column are the same but the dates are all different.

**Comment by m4rc3l** [comment]
OK, got the Problem, but dont have a solution yet.
Cryptofinance need it in this format:
=CRYPTOFINANCE(C10&"/"&CONFIG!$C$8, "price","2017-12-07")

So I guess if you want to put in a cell number for the date, that have to be in the plain text format.
When there is an error somehow, the output will give you the actual price

**Comment by m4rc3l** [comment]
LOL, OK... Simple as that:

The cells in the Date column have to be formated as "plain Text"  
Format>Number>Plain Text

**Comment by m4rc3l** [comment]
You can check my sheet and see if there is a difference ...

https://docs.google.com/spreadsheets/d/1VbZ96H4QN9secuA-Tw21DjGQ677f39uyuW0TPNPFSFM/edit?usp=sharing

**Comment by m4rc3l** [comment]
The formula has to be like this : =CRYPTOFINANCE(C8 & "/" &CONFIG!$C$8, "price", B8)

**Comment by inoxi** [comment]
All good now. Thank you! There are some extra spaces. My formula was =CRYPTOFINANCE(C8&"/" &CONFIG!$C$8, "price", B8) with no spaces between C8 and & and "/"

But now it's working fine. Thanks again!

**Comment by chrisek** [comment]
@inoxi Do you still need assistance ?

**Comment by inoxi** [comment]
@chrisek all good now. The formula pasted by @m4rc3l works very good.
