### ISSUE TITLE
Still not adding up

### ISSUE THREAD

**Issue by cryptroid** [chrisek/PT_Tracker#15]
I copy and paste my sales log into the PT Dump. 

a) it doesn't immediately show the SOLD PRICE as a BTC number it shows it as a $ amount.  

b) when set it to Automatic it then pulls it in as a number instead of just saying $0.00

c) when you go to the dashboard it is showing me numbers I know are WAY OFF. See below screen shots.  These should be more like 1.83% daily profit and average daily USD profit like around $100.
<img width="266" alt="screen shot 2018-01-19 at 9 13 09 pm" src="https://user-images.githubusercontent.com/35219101/35180169-ea24e5c0-fd5e-11e7-992e-7aa30caf37ed.png">
<img width="294" alt="screen shot 2018-01-19 at 9 19 51 pm" src="https://user-images.githubusercontent.com/35219101/35180170-ea3bad00-fd5e-11e7-9d17-fd8a6effabd0.png">

**Comment by chrisek** [comment]
Google in supporting only BTC price, thats why i have implenmented workaround. Have you installed addon?
https://jbuty.com/how-to-get-crypto-currencies-rates-and-more-in-google-sheet-1a57e571bc14

**Comment by m4rc3l** [comment]
I cant see what exactly your problem is... But the first thing I see is, that your starting date is not correct, so the fist month is wrong and 0 and the issue adds up from there...

**Comment by chrisek** [comment]
@cryptroid Do you still have this issue ? Can you share link to your spreadsheet in private, i will take a closer look?
