### ISSUE TITLE
All Issues solved so far

### ISSUE THREAD

**Issue by m4rc3l** [chrisek/PT_Tracker#16]
I got all know issues solved in my version now. Its working with different currencies in FIAT and Crypto and I also fixed the overall calculation of profit, but I dont know how I can contribute that all to your sheet.... Let me know what the easiest way is.

**Comment by Mulct** [comment]
Release a new version? Upload it somewhere?

**Comment by m4rc3l** [comment]
I forked the sheet:  https://github.com/m4rc3l/PT_Tracker

**Comment by chrisek** [comment]
So what did you changed ?

**Comment by m4rc3l** [comment]
I added these cells, so that the function is not needed in the colums. And I added the coulum titles that use now the chosen currency...
![image](https://user-images.githubusercontent.com/35396758/35198797-63cf08ce-fef4-11e7-97b6-c68be7552083.png)

Total Value is now also calculated with actual crypto rate....

and I had to change the hidden column... cause another cryptofinance function gave me a lot of rate errors of api querries... I still have to figure out the precise problem...

![image](https://user-images.githubusercontent.com/35396758/35198829-df193be4-fef4-11e7-9c50-7677b4e3bfaf.png)

**Comment by chrisek** [comment]
All issues have been implemented and corrected in 0.07
