### ISSUE TITLE
Support for different currencys?

### ISSUE THREAD

**Issue by Mulct** [chrisek/PT_Tracker#4]
Would be nice if we could use other currency's

**Comment by m4rc3l** [comment]
I did that to mine, since I use ETH and also EUR... You just need the Add-on Cryptofinance and you can use different cryptos and even more than just price of it...

**Comment by chrisek** [comment]
This is the next feature i work on setup tab where you could change FIAT and Altcoin your bot is using.

**Comment by m4rc3l** [comment]
Would be cool, if you could change currencies as well..

**Comment by Mulct** [comment]
Is it possible to add a cell with your current total btc, instead of having to look at the total capital chart.

**Comment by chrisek** [comment]
Its done in latest release, please chceck if everythink is like supposed:

https://docs.google.com/spreadsheets/d/1jOM5In5p6O8jO285n5wTKPU1p-k-rzsJ8m_9RuzxZ9c/edit?usp=sharing

**Comment by spanznet** [comment]
Possible to add AUD?

**Comment by Mulct** [comment]
In latest version 0.06.2 whenever switching to GBP or euro the spreadsheet breaks.

getting errors like: Function ADD parameter 2 expects number values. But '£490.40' is a text and cannot be coerced to a number.

**Comment by m4rc3l** [comment]
Did you install the Cryptofinance add-on?

**Comment by Mulct** [comment]
Yeah I installed the add-on. I use the add on on my own spreadsheets

**Comment by Mulct** [comment]
Here is a link : https://docs.google.com/spreadsheets/d/1M3FgZ1nRs_GuFZLwPBJVclsqBQGQ4AIp5BwI265T7Q0/edit?usp=sharing

**Comment by m4rc3l** [comment]
That doesnt help cause I cant see or change the format or currency cells...

**Comment by Mulct** [comment]
Try this: https://docs.google.com/spreadsheets/d/1M3FgZ1nRs_GuFZLwPBJVclsqBQGQ4AIp5BwI265T7Q0/edit?usp=sharing

**Comment by m4rc3l** [comment]
Weird... I cant tell what the problem is, but in your Dashboard cell D14 the "Format" menu is greyed out, which is not the case in my sheet...

**Comment by m4rc3l** [comment]
It seem like something is different from the original but I dont know what you changed... you should start over from scratch i think

**Comment by m4rc3l** [comment]
I forked the sheet to my working one until chrisek has updated his...

https://github.com/m4rc3l/PT_Tracker

**Comment by chrisek** [comment]
Included in v0.07
