### ISSUE TITLE
Deposit tab

### ISSUE THREAD

**Issue by github-4me** [chrisek/PT_Tracker#5]
I see you are using =GOOGLEFINANCE("btcusd") but I feel it is in the wrong place, this should be in a cell by itself because D7 in your chart is not BTC but USD and then you sum this in H4 which in BTC.
Units would be in BTC and yo have USD.  So move formula to G2 or simliar.   I would add  F7 as a BTC price which would use =GOOGLEFINANCE("btcusd") to subtract from E7 to show your loss or gain from original purchase from the date entered. I feel this is more accurate representation of profit and loss.
great job so far thou.

**Comment by dimmyr** [comment]
Agreed. Ideally, the conversion to USD column should reflect the historical rate, and not today's rate.

**Comment by chrisek** [comment]
Im doing Config tab with currency preferences for dashboard, take a look: 

https://docs.google.com/spreadsheets/d/1DJlREBTlrDvQMUpootwonPBTd3hkvoJf_mGHQ4kw9dU/edit?usp=sharing

**Comment by chrisek** [comment]
Done.
