### ISSUE TITLE
Google Addon

### ISSUE THREAD

**Issue by dimmyr** [chrisek/PT_Tracker#6]
Just a suggestion - consider using the more advanced CRYPTOFINANCE() function, available as a Google Sheets Add-On, uses the coinmarketcap API to returns the rates, market cap, volume, change, total supply, and rank.  It allows you to get rates for other coins than BTC, and get historical data.

https://jbuty.com/how-to-get-crypto-currencies-rates-and-more-in-google-sheet-1a57e571bc14

Here's how the deposit calculations would look like with that function.  The question is, should you re-do the daily profit calculations based on the historical prices as opposed the current price.  I think that's a better way of calculating profit, personally...
![image](https://user-images.githubusercontent.com/8550213/34928190-816c7b28-f981-11e7-9614-49ca0be3e695.png)

**Comment by chrisek** [comment]
I agree, the use of this addon would be great, I just have doubts if it will not complicate this file too much. Many people are not familiar with Google spreadsheet and adding another condition, the addon will complicate matters even more. I need to think how best to do it.

**Comment by chrisek** [comment]
Its Added to the lates release, lets see how it works :) 

https://docs.google.com/spreadsheets/d/1jOM5In5p6O8jO285n5wTKPU1p-k-rzsJ8m_9RuzxZ9c/edit?usp=sharing
