### ISSUE TITLE
Markets

### ISSUE THREAD

**Issue by anknarsi** [chrisek/PT_Tracker#8]
Can you have this compatible with binance coin market BNB?   Also how do I make this my own and use it?  I requested permission to edit and when I download it as an excel file it says the file is corrupted.  Thanks

**Comment by chrisek** [comment]
Its working on every market where profit trailer works. If you want to have your own spreadsheet just go to File ->Make a Copy and then you are owner of your local file.

**Comment by anknarsi** [comment]
Its still only showing USDT, ETH and BTC.  Not BNB, how can I add this?
